name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  apply:
    permissions:
      contents: read
      id-token: write

    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:githubactions-tf-hashicorp-vault

      - name: Auth GCP
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/455628669441/locations/global/workloadIdentityPools/github-actions/providers/gha-tf-hashicorp-vault'

      - uses: smallstep/action-install-step-cli@v1

      - name: Bootstrap Step CLI
        run: sudo step ca bootstrap --install --ca-url https://cuboid-topi.rmb1993-gmail-com.ca.smallstep.com --fingerprint eb136a5118931a2306964469705323521dda8c43d26ec67e1c5508eb123f9c70

      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v3
        with:
          url: https://hashi-vault.tailnet-047c.ts.net:8200
          role: gha_rmb938_tf_hashicorp_vault
          method: jwt
          path: jwt-gha
          exportToken: true

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.3"

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check -diff

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        env:
          TAILSCALE_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          TAILSCALE_OAUTH_CLIENT_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
        run: terraform plan -out tfplan

      - name: Terraform Apply
        env:
          TAILSCALE_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          TAILSCALE_OAUTH_CLIENT_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
        run: terraform apply tfplan

      # https://github.com/hashicorp/vault-action/issues/427
      - name: Revoke Vault Token
        if: always()
        run: |
          curl -XPOST -sv -H "X-Vault-Token: ${{ env.VAULT_TOKEN }}" https://hashi-vault.tailnet-047c.ts.net:8200/v1/auth/token/revoke-self 